name: Mark stale issues and pull requests

on:
  issues:
    types: [opened]

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v3
      with:
        stale-issue-message: 'Issue has not been investigated and will be closed in 10 days.'
        stale-pr-message: 'PR has not been investigated and will be closed in 10 days.'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
        days-before-stale: 5
        exempt-assignees: "Ekultek"
